topicals2_Options = {
    queries_maxEntries: [5,4,2,3], /*  <-- array length USED as table row count */
    queries_sort_key: 'POPULAR', /* can only be 'NAME' 'POPULAR' 'PRICE' 'POTENCY' */
    queries_filter_category: [],
    queries_filter_subcategory: [ 'OIL','CAPSULES_TABLETS','LOTIONS','BATH_PRODUCTS' ],
    queries_filter_strainType: [],
    showCBDPotencyColumn : true,
    showTHCPotencyColumn : true,
    showStrainTypeColumn : true,
    enableTaxInPricing : true,
    legendColorSale: 'rgb(4, 122, 4)',
    legendColorLimited: 'red',
    enableStripedTables : true,
    includeProductShot : false,
    includeLegend : true,
    ignoreNAUnitSize : true,
    enableUnitStrippingFromNames : false,
    enableSplitMenu : false,
    enablePotencyAsIcons : false,
    enablePotencySanityCheck  : false,
    enableDebugToConsole : true,
    showLoadingMessage : false
},
edibles2_Options = {
  queries_maxEntries: [12,9,8,7], /*  <-- array length USED as table row count */
  queries_sort_key: 'POPULAR',
  queries_filter_category: [],
  queries_filter_subcategory: [ 'DRINKS','CHOCOLATES','CHEWS','GUMMIES' ],
  queries_filter_strainType: [],
  showCBDPotencyColumn : true,
  showTHCPotencyColumn : true,
  showStrainTypeColumn : true,
  enableTaxInPricing : true,
  legendColorSale: 'rgb(4, 122, 4)',
  legendColorLimited: 'red',
  enableStripedTables : true,
  includeProductShot : false,
  includeLegend : true,
  ignoreNAUnitSize : true,
  enableUnitStrippingFromNames : false,
  enableSplitMenu : false,
  enablePotencyAsIcons : false,
  enablePotencySanityCheck  : false,
  enableDebugToConsole : true,
  showLoadingMessage : false
},
flower2_Options = {
  queries_maxEntries: [12,9,8,7], /*  <-- array length USED as table row count */
  queries_sort_key: 'POPULAR',
  queries_filter_category: ['FLOWER','FLOWER', 'FLOWER', ''],
  queries_filter_subcategory: ['','','','PRE_GROUND'],
  queries_filter_strainType: ['HYBRID', 'INDICA', 'SATIVA', ''],
  showCBDPotencyColumn : false,
  showTHCPotencyColumn : false,
  showStrainTypeColumn : true,
  includeProductShot : true,
  includeLegend : true,
  legendColorSale: 'rgb(4, 122, 4)',
  legendColorLimited: 'red',
  enableTaxInPricing : true,
  enableStripedTables : false,
  ignoreNAUnitSize : true,
  enableUnitStrippingFromNames : false,
  enablePotencyAsIcons : false,
  enablePotencySanityCheck  : false,
  enableSplitMenu : false,
  showLoadingMessage : false,
  enableDebugToConsole : true
},
xtrax2_Options = {
  queries_maxEntries: [8,3,2,2,2], /*  <-- array length USED as table row count */
  queries_sort_key: 'POPULAR',
  queries_filter_category: [],
  queries_filter_subcategory: [ 'CARTRIDGES','HASH','LIVE_RESIN','KIEF','SHATTER'],
  queries_filter_strainType: [],
  showCBDPotencyColumn : false,
  showTHCPotencyColumn : true,
  showStrainTypeColumn : false,
  enableTaxInPricing : true,
  legendColorSale: 'rgb(4, 122, 4)',
  legendColorLimited: 'red',
  enableStripedTables : true,
  includeProductShot : true,
  includeLegend : true,
  ignoreNAUnitSize : true,
  enableUnitStrippingFromNames : false,
  enableSplitMenu : true,
  enablePotencyAsIcons : false,
  enablePotencySanityCheck  : false,
  enableDebugToConsole : true,
  showLoadingMessage : false
},
prerolls2_Options = {
  queries_maxEntries: [35], /*  <-- array length USED as table row count */
  queries_sort_key: 'PRICE',
  queries_filter_category: ['PRE_ROLLS'],
  queries_filter_subcategory: [],
  queries_filter_strainType: [],
  showCBDPotencyColumn : false,
  showTHCPotencyColumn : true,
  showStrainTypeColumn : false,
  enableTaxInPricing : true,
  legendColorSale: 'rgb(4, 122, 4)',
  legendColorLimited: 'red',
  enableStripedTables : true,
  includeProductShot : true,
  includeLegend : true,
  ignoreNAUnitSize : true,
  enableUnitStrippingFromNames : false,
  enableSplitMenu : true,
  enablePotencyAsIcons : false,
  enablePotencySanityCheck  : false,
  enableDebugToConsole : true,
  showLoadingMessage : false
}
